version: '3'
services:
  app:
    image: "nginx:1.18.0"
    tty: true
    expose:
      - "80"
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
      - "./env/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./env/nginx/conf.d:/etc/nginx/conf.d"
    working_dir: /var/www
    depends_on:
      - php
    networks:
      - terrace
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/var/www
      - ./env/php/php-fpm.d/custom.ini:/usr/local/etc/php-fpm.d/custom.ini
      - "./env/php/custom.ini:/usr/local/etc/php/custom.ini"
    working_dir: /var/www
    expose:
      - 9000
    # depends_on:
    #  - mysql
    links: 
      - mysql
    networks:
      - terrace
  mysql:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
     - "3360:3006"
    #user: mysql
    volumes:
     - ./mysql:/var/lib/mysql
     - "./backups/init:/docker-entrypoint-initdb.d"
    networks:
     - terrace
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #    - "81:80"
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   networks:
  #    - terrace
volumes:
  mysql:
networks:
  terrace:
