version: '3'
services:
  webserver:
    image: "nginx:1.18.0"
    container_name: terrace-webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - "./env/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./env/nginx/conf.d:/etc/nginx/conf.d"
    working_dir: /var/www
    depends_on:
      - php
    networks:
      - terrace
    expose:
      - "9000"
  php:
    image: terrace/php:8.1-fpm
    container_name: terrace-php
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/var/www
      - "./env/php/php-fpm.d/custom.ini:/usr/local/etc/php-fpm.d/custom.ini"
    working_dir: /var/www
    expose:
      - 9000
    links: 
      - mysql
    networks:
      - terrace
  mysql:
    image: "mysql:5.7"
    container_name: terrace-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
     - "3360:3006"
    volumes:
     - ./mysql:/var/lib/mysql
     - "./backups/data.sql:/docker-entrypoint-initdb.d/data.sql"
    networks:
     - terrace
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: terrace-elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    env_file: env/elasticsearch/elasticsearch.env
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - terrace
  redis:
    image: redis:6.2
    container_name: terrace-redis
    tty: true
    ports:
      - "6378:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - terrace
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: terrace-phpmyadmin
    restart: always
    ports:
     - "81:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
     - terrace
volumes:
  mysql:
networks:
  terrace:
