version: '3'
services:
  app:
    image: "nginx:1.18.0"
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - "./env/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./env/nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - php
    networks:
      - terrace
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - .:/var/www/html
      - "./env/php/php-fpm/php.conf:/usr/local/etc/php-fpm/php.conf"
    working_dir: /var/www/html
    # entrypoint: [ "bash", "-c", "/start.sh"]
    depends_on:
     - mysql
    links: 
      - mysql
    networks:
      - terrace
  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
     - "3360:3006"
    volumes:
     - ./mysql:/var/lib/mysql
    networks:
     - terrace
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - "81:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
     - terrace
volumes:
  mysql:
networks:
  terrace:
